"""add employee_meetings association table

Revision ID: b03eb772b706
Revises: 4e22cbfd73af
Create Date: 2023-11-14 09:16:53.751897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03eb772b706'
down_revision = '4e22cbfd73af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_meetings',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('meetings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employees_meetings_employee_id_employees')),
    sa.ForeignKeyConstraint(['meetings_id'], ['meetings.id'], name=op.f('fk_employees_meetings_meetings_id_meetings')),
    sa.PrimaryKeyConstraint('employee_id', 'meetings_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_meetings')
    # ### end Alembic commands ###
